### PR TITLE
Enable merge-multiple on upload-arifacts

### PR DESCRIPTION
**Pull request by SuperQ**
Allow uploading all tarballs in `save_artifacts`.

### CODE REVIEW

**Comment by SuperQ** [comment]
:eyeglasses: @mmorel-35

**Review by Nexucis — APPROVED** [review]

**Comment by Nexucis** [comment]
@SuperQ don't you need to modify https://github.com/prometheus/promci/blob/main/actions/restore_artifacts/action.yml to use the name "tarballs" ?

**Comment by SuperQ** [comment]
Oh, good catch.

**Comment by SuperQ** [comment]
Closing in favor of #12

**Pull request closed without merging**
